apiVersion: v1
kind: Secret
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    prometheus: k8s
  name: alertmanager-alertmanager-main
  namespace: {{ .Values.global.namespace | .Release.Namespace }}
data:
  alertmanager.yaml: {{ .Files.Get "config/alertmanager.yml.tpl" | b64enc | quote }}

