apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "1"
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: prometheus-get-crd
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  template:
    metadata:
      name: prometheus-job-get-crd
    spec:
      containers:
        - name: hyperkube
          image: quay.io/coreos/hyperkube:v1.8.5_coreos.0
          imagePullPolicy: IfNotPresent
          command:
            - ./kubectl
            - get
            - customresourcedefinitions
            - alertmanagers.monitoring.coreos.com
            - prometheuses.monitoring.coreos.com
            - servicemonitors.monitoring.coreos.com
      restartPolicy: OnFailure
      serviceAccountName: prometheus-operator
