apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    k8s-app: kube-controller-manager
    release: {{ .Release.Name | quote }}
  name: kube-controller-manager
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  jobLabel: k8s-app
  endpoints:
  - port: http-metrics
    interval: 30s
  selector:
    matchLabels:
      k8s-app: kube-controller-manager
  namespaceSelector:
    matchNames:
    - kube-system

