apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Name | quote }}
    k8s-app: kube-state-metrics
    release: {{ .Release.Name | quote }}
  name: kube-state-metrics
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
