apiVersion: v1
kind: Service
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    k8s-app: node-exporter
    release: {{ .Release.Name | quote }}
  name: node-exporter
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  selector:
    k8s-app: node-exporter
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: {{ .Values.nodeExporter.service.port }}
    protocol: TCP
    targetPort: metrics
