apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Name | quote }}
    k8s-app: node-exporter
    release: {{ .Release.Name | quote }}
  name: node-exporter
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
