apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    k8s-app: node-exporter
    release: {{ .Release.Name | quote }}
  name: node-exporter
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: node-exporter
    spec:
      serviceAccountName: node-exporter
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      hostNetwork: true
      hostPID: true
      containers:
      - image: {{ .Values.nodeExporter.image.name }}:{{ .Values.nodeExporter.image.tag }}
        args:
        - "--web.listen-address=0.0.0.0:{{ .Values.nodeExporter.service.targetPort }}"
        - "--path.procfs=/host/proc"
        - "--path.sysfs=/host/sys"
        name: node-exporter
        ports:
        - containerPort: {{ .Values.nodeExporter.service.targetPort }}
          hostPort: {{ .Values.nodeExporter.service.hostPort }}
          name: metrics
        resources:
{{ toYaml .Values.nodeExporter.resources | indent 12 }}
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
#      - name: kube-rbac-proxy
#        image: quay.io/brancz/kube-rbac-proxy:v0.2.0
#        args:
#        - "--secure-listen-address=:9100"
#        - "--upstream=http://127.0.0.1:9101/"
#        ports:
#        - containerPort: 9100
#          hostPort: 9100
#          name: https
#        resources:
#          requests:
#            memory: 20Mi
#            cpu: 10m
#          limits:
#            memory: 40Mi
#            cpu: 20m
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
