{{- if .Values.prometheus.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    k8s-app: prometheus
    prometheus: k8s
    release: {{ .Release.Name | quote }}
  name: prometheus
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: prometheus
      prometheus: k8s
  namespaceSelector:
    matchNames:
    - {{ .Values.global.namespace | default .Release.Namespace }}
  endpoints:
  - port: web
    scheme: http
    interval: 30s
{{- end }}
