apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    k8s-app: prometheus
    prometheus: k8s
    release: {{ .Release.Name | quote }}
  name: prometheus
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
  - name: web
    port: {{ .Values.prometheus.service.port }}
    targetPort: web
    protocol: TCP
  selector:
    prometheus: k8s
    app: prometheus
