{{- if .Values.global.storage.enabled }}
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    prometheus: k8s
    release: {{ .Release.Name | quote }}
  name: {{ .Values.global.storage.storageClassName }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
provisioner: {{ .Values.global.storage.provisioner }}
parameters:
{{- range $key, $val := .Values.global.storage.parameters }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
